name: todo
description: Yusir
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.16.1
  path_provider: ^1.6.27
  sqflite: ^1.3.2+2
  cupertino_icons: ^1.0.1
  transformer_page_view: ^0.1.6
  dots_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true